# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shift Pro League
email: gabe@shiftpl.com
description: > # ignore newlines until next property
  Shift Pro League was established in March of 2016 as a place
  where players of all skill levels can come together for weekly matchups.
repository: shift/willis2342.github.io
collections:
  eu:
    layout: post
    permalink: /eu/:title/
  na:
    layout: post
    permalink: /na/:title/

# Social Media
battlefy_username: shift-pro-league
discord_username: shiftpl
# matcherino:
patreon_username: shiftpl
twitch_username: ShiftProLeague
twitter_username: ShiftProLeague

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "/shift" # does not include hostname
url: "https://willis2342.github.io/shift/"

# Outputting
permalink: /:categories/:title/
# permalink:     date
# paginate_path: /page:num
# timezone:      null

# quiet:    false
# defaults: []

# Build settings
markdown: kramdown
